import { Listing } from './types';

export const SAMPLE_LISTINGS: Listing[] = [
  {
    id: 'sample-1',
    source: 'PropertyGuru',
    title: '2 Room HDB For Rent - Jurong West',
    price: 2200,
    bedrooms: 2,
    bathrooms: 1,
    floorSize: 50,
    address: 'Block 653C, Jurong West Street 61',
    area: 'Jurong West',
    propertyType: 'HDB',
    url: 'https://www.propertyguru.com.sg/listing/hdb-for-rent-653c-jurong-west-street-61-500141804',
    imageUrl: '',
    nearestMrt: 'Pioneer MRT',
    postedDate: '2026-06-01',
    agentName: 'Sample Agent',
  },
  {
    id: 'sample-2',
    source: 'PropertyGuru',
    title: '2 Room HDB For Rent - Boon Lay',
    price: 2400,
    bedrooms: 2,
    bathrooms: 1,
    floorSize: 55,
    address: 'Block 175, Boon Lay Drive',
    area: 'Boon Lay',
    propertyType: 'HDB',
    url: 'https://www.propertyguru.com.sg/listing/hdb-for-rent-boon-lay',
    imageUrl: '',
    nearestMrt: 'Boon Lay MRT',
    postedDate: '2026-06-03',
    agentName: 'Sample Agent',
  },
  {
    id: 'sample-3',
    source: 'PropertyGuru',
    title: '2 Room Condo For Rent - Clementi',
    price: 2800,
    bedrooms: 2,
    bathrooms: 2,
    floorSize: 65,
    address: 'The Clement Canopy, Clementi Avenue 1',
    area: 'Clementi',
    propertyType: 'Condo',
    url: 'https://www.propertyguru.com.sg/listing/condo-for-rent-clementi',
    imageUrl: '',
    nearestMrt: 'Clementi MRT',
    postedDate: '2026-06-05',
    agentName: 'Sample Agent',
  },
  {
    id: 'sample-4',
    source: 'PropertyGuru',
    title: '2 Room HDB For Rent - Bukit Batok',
    price: 1900,
    bedrooms: 2,
    bathrooms: 1,
    floorSize: 48,
    address: 'Block 210, Bukit Batok Street 21',
    area: 'Bukit Batok',
    propertyType: 'HDB',
    url: 'https://www.propertyguru.com.sg/listing/hdb-for-rent-bukit-batok',
    imageUrl: '',
    nearestMrt: 'Bukit Batok MRT',
    postedDate: '2026-06-02',
    agentName: 'Sample Agent',
  },
  {
    id: 'sample-5',
    source: 'PropertyGuru',
    title: '2 Room HDB For Rent - Pioneer',
    price: 2000,
    bedrooms: 2,
    bathrooms: 1,
    floorSize: 50,
    address: 'Block 959, Pioneer Road North',
    area: 'Pioneer',
    propertyType: 'HDB',
    url: 'https://www.propertyguru.com.sg/listing/hdb-for-rent-pioneer',
    imageUrl: '',
    nearestMrt: 'Pioneer MRT',
    postedDate: '2026-06-04',
    agentName: 'Sample Agent',
  },
  {
    id: 'sample-6',
    source: 'PropertyGuru',
    title: '2 Room HDB For Rent - Choa Chu Kang',
    price: 1700,
    bedrooms: 2,
    bathrooms: 1,
    floorSize: 45,
    address: 'Block 485, Choa Chu Kang Avenue 5',
    area: 'Choa Chu Kang',
    propertyType: 'HDB',
    url: 'https://www.propertyguru.com.sg/listing/hdb-for-rent-choa-chu-kang',
    imageUrl: '',
    nearestMrt: 'Choa Chu Kang MRT',
    postedDate: '2026-06-01',
    agentName: 'Sample Agent',
  },
  {
    id: 'sample-7',
    source: 'PropertyGuru',
    title: '2 Room HDB For Rent - Tengah',
    price: 2100,
    bedrooms: 2,
    bathrooms: 1,
    floorSize: 52,
    address: 'Block 123, Tengah Drive',
    area: 'Tengah',
    propertyType: 'HDB',
    url: 'https://www.propertyguru.com.sg/listing/hdb-for-rent-tengah',
    imageUrl: '',
    nearestMrt: 'Tengah Plantation MRT (future)',
    postedDate: '2026-06-06',
    agentName: 'Sample Agent',
  },
  {
    id: 'sample-8',
    source: 'PropertyGuru',
    title: '2 Room HDB For Rent - Jurong West',
    price: 2500,
    bedrooms: 2,
    bathrooms: 2,
    floorSize: 60,
    address: 'Block 456, Jurong West Street 42',
    area: 'Jurong West',
    propertyType: 'HDB',
    url: 'https://www.propertyguru.com.sg/listing/hdb-for-rent-jurong-west-2',
    imageUrl: '',
    nearestMrt: 'Pioneer MRT',
    postedDate: '2026-06-05',
    agentName: 'Sample Agent',
  },
  {
    id: 'sample-9',
    source: 'PropertyGuru',
    title: '2 Room Condo For Rent - Bukit Panjang',
    price: 2600,
    bedrooms: 2,
    bathrooms: 2,
    floorSize: 70,
    address: 'Segar Court, Bukit Panjang',
    area: 'Bukit Panjang',
    propertyType: 'Condo',
    url: 'https://www.propertyguru.com.sg/listing/condo-for-rent-bukit-panjang',
    imageUrl: '',
    nearestMrt: 'Bukit Panjang MRT',
    postedDate: '2026-06-03',
    agentName: 'Sample Agent',
  },
  {
    id: 'sample-10',
    source: 'PropertyGuru',
    title: '2 Room HDB For Rent - Boon Lay',
    price: 2300,
    bedrooms: 2,
    bathrooms: 1,
    floorSize: 53,
    address: 'Block 221, Boon Lay Place',
    area: 'Boon Lay',
    propertyType: 'HDB',
    url: 'https://www.propertyguru.com.sg/listing/hdb-for-rent-boon-lay-2',
    imageUrl: '',
    nearestMrt: 'Boon Lay MRT',
    postedDate: '2026-06-06',
    agentName: 'Sample Agent',
  },
];
